//
//  ListaAlumnosConfigurator.swift
//  Asistencia
//
//  Created by Fabrizio on 9/4/19.
//  Copyright (c) 2019 Fabrizio Valdivia. All rights reserved.
//
//  This file was generated by the StartApps CleanSwift Xcode Templates. V2.0
//  By Gabriel Lanata (http://StartApps.pe) with credit to http://clean-swift.com
//

import UIKit

// MARK: - Connect View, Interactor, and Presenter

extension ListaAlumnosViewController {

    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        router.passDataToNextScene(segue: segue)
    }

    override func awakeFromNib() {
        super.awakeFromNib()
        ListaAlumnosConfigurator.configure(viewController: self)
    }

    static func instantiate() -> ListaAlumnosViewController {
        let storyboard = UIStoryboard(name: "ListaAlumnos", bundle: nil)
        let viewController = storyboard.instantiateInitialViewController() as! ListaAlumnosViewController
        return viewController
    }

}

class ListaAlumnosConfigurator {

    // MARK: - Configuration

    static func configure(viewController: ListaAlumnosViewController) {

        let presenter = ListaAlumnosPresenter()
        presenter.viewController = viewController

        let interactor = ListaAlumnosInteractor()
        interactor.presenter = presenter

        let router = ListaAlumnosRouter()
        router.viewController = viewController
        router.interactor = interactor

        viewController.interactor = interactor
        viewController.router = router
    }

}
