//
//  ListaAlumnosModels.swift
//  Asistencia
//
//  Created by Fabrizio on 9/4/19.
//  Copyright (c) 2019 Fabrizio Valdivia. All rights reserved.
//
//  This file was generated by the StartApps CleanSwift Xcode Templates. V2.0
//  By Gabriel Lanata (http://StartApps.pe) with credit to http://clean-swift.com
//

import Foundation

enum ListaAlumnosScene {
    
    enum Alumnos {
        
        struct Request {
        }
        struct Response {
            let alumnos: [Alumno]
            
        }
        struct ViewModel {
            struct DisplayedAlumno {
                let name: String
                let email: String
                let phone: String
                let id: String
                let dni: String
                var attendance: [String: Bool]
            }
            let displayedAlumnos: [DisplayedAlumno]
        }
        
    }
    
    enum AlertError {
        
        struct Response {
            let error: Error
        }
        struct ViewModel {
            let message: String
        }
        
    }

}
