//
//  ListaAlumnosRouter.swift
//  Asistencia
//
//  Created by Fabrizio on 9/4/19.
//  Copyright (c) 2019 Fabrizio Valdivia. All rights reserved.
//
//  This file was generated by the StartApps CleanSwift Xcode Templates. V2.0
//  By Gabriel Lanata (http://StartApps.pe) with credit to http://clean-swift.com
//

import UIKit

//@available(iOS 13.0, *)
class ListaAlumnosRouter {

    weak var viewController: ListaAlumnosViewController?
    weak var interactor: ListaAlumnosInteractor?

    // MARK: - Navigation

    func navigateToSomewhere(nombre: String, correo: String, telefono: String) {
        // NOTE: Teach the router how to navigate to another scene. Some examples follow:

        // 1. Trigger a storyboard segue
        // viewController?.performSegueWithIdentifier("ShowSomewhereScene", sender: nil)

        // 2. Present another view controller programmatically
        // viewController?.presentViewController(someWhereViewController, animated: true, completion: nil)

        // 3. Ask the navigation controller to push another view controller onto the stack
        // viewController?.navigationController?.pushViewController(someWhereViewController, animated: true)

        // 4. Present a view controller from a different storyboard
        // let storyboard = UIStoryboard(name: "OtherThanMain", bundle: nil)
        // let someWhereViewController = storyboard.instantiateInitialViewController() as! SomeWhereViewController
        // viewController?.navigationController?.pushViewController(someWhereViewController, animated: true)

        // 5. Present a view controller from a different storyboard the StartApps way (preferred)
        // let someWhereViewController = SomeWhereViewController.instantiate()
        // viewController?.navigationController?.pushViewController(someWhereViewController, animated: true)
        
        let storyboard = UIStoryboard(name: "PopUp", bundle: nil)
        let popUpViewController = storyboard.instantiateViewController(withIdentifier: "popUpView") as! PopUpViewController
        popUpViewController.nombre = nombre
        popUpViewController.correo = correo
        popUpViewController.telefono = telefono
        
//        viewController?.navigationController?.pushViewController(popUpViewController, animated: true)
        
        popUpViewController.modalPresentationStyle = .overFullScreen
        popUpViewController.modalTransitionStyle = .crossDissolve
        viewController?.present(popUpViewController, animated: true, completion: nil)
    }
    
    func navigateToAdd (id: Int, fechas: [EventDate], count: Int, attendeeType: [String]) {
        let storyboard = UIStoryboard(name: "AgregarAlumno", bundle: nil)
        let agregarAlumnoVC = storyboard.instantiateViewController(withIdentifier: "AgregarAlumno") as! AgregarAlumno
        agregarAlumnoVC.id = id
        agregarAlumnoVC.fechas = fechas
        agregarAlumnoVC.count = count
        agregarAlumnoVC.pickOption = attendeeType
        self.viewController?.present(UINavigationController(rootViewController: agregarAlumnoVC), animated: true, completion: nil)
    }
    
    func navigateToScanner () {
        let storyboard = UIStoryboard(name: "QRScanner", bundle: nil)
        let QRScannerVC = storyboard.instantiateViewController(withIdentifier: "QRScanner") as! ScannerViewController
//        self.viewController?.navigationController?.pushViewController(QRScannerVC, animated: true)
        let vc = UINavigationController(rootViewController: QRScannerVC)
        vc.modalPresentationStyle = .fullScreen
//        self.viewController?.present(UINavigationController(rootViewController: QRScannerVC), animated: true, completion: nil)
        self.viewController?.present(vc, animated: true, completion: nil)
    }
    
    func navigateToNotFound() {
        let storyboard = UIStoryboard(name: "QRNotFound", bundle: nil)
        let popUpViewController = storyboard.instantiateViewController(withIdentifier: "QRNotFound") as! QRNotFoundViewController
        popUpViewController.modalPresentationStyle = .overFullScreen
        popUpViewController.modalTransitionStyle = .crossDissolve
        viewController?.present(popUpViewController, animated: true, completion: nil)
    }
    
    func navigateToCompletion(nombreA: String, correoA: String, id: Int, fechas: [EventDate], idAlumno: String, attendanceRaw: [String: Bool]) {
        let storyboard = UIStoryboard(name: "PopupCompletion", bundle: nil)
        let popUpViewController = storyboard.instantiateViewController(withIdentifier: "PopupCompletion") as! PopupCompletionViewController
        popUpViewController.modalPresentationStyle = .overFullScreen
        popUpViewController.modalTransitionStyle = .crossDissolve
        popUpViewController.nombreA = nombreA
        popUpViewController.correoA = correoA
        popUpViewController.idEvento = id
        popUpViewController.fechasEvento = fechas
        popUpViewController.idAlumno = idAlumno
        popUpViewController.attendanceRaw = attendanceRaw
        viewController?.present(popUpViewController, animated: true, completion: nil)
    }

    // MARK: - Communication

    func passDataToNextScene(segue: UIStoryboardSegue) {
        // NOTE: Teach the router how to pass data to the next scene
        // if let destinationViewController = segue.destination as? SomewhereViewController {
        //     destinationViewController.interactor.something = interactor?.something
        // }
    }

}
