//
//  EventosModels.swift
//  Asistencia
//
//  Created by Fabrizio on 9/4/19.
//  Copyright (c) 2019 Fabrizio Valdivia. All rights reserved.
//
//  This file was generated by the StartApps CleanSwift Xcode Templates. V2.0
//  By Gabriel Lanata (http://StartApps.pe) with credit to http://clean-swift.com
//

import Foundation

enum EventosScene {
    
    enum Eventos {
        
        struct Request {
        }
        struct Response {
            let events: [Evento]
        }
        struct ViewModel {
            struct DisplayedEvent {
                let name: String
                let color: String
                let image: String
                let id: Int
                let dateHidden: String
                let canAddAttendee: Bool
                let dates: [EventDate]
                let attendeeType: [String]
            }
            let displayedEvents: [DisplayedEvent]
        }
        
    }
    
    enum AlertError {
        
        struct Response {
            let error: Error
        }
        struct ViewModel {
            let message: String
        }
        
    }

}
