//
//  EventosConfigurator.swift
//  Asistencia
//
//  Created by Fabrizio on 9/4/19.
//  Copyright (c) 2019 Fabrizio Valdivia. All rights reserved.
//
//  This file was generated by the StartApps CleanSwift Xcode Templates. V2.0
//  By Gabriel Lanata (http://StartApps.pe) with credit to http://clean-swift.com
//

import UIKit

// MARK: - Connect View, Interactor, and Presenter

extension EventosViewController {

    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        router.passDataToNextScene(segue: segue)
    }

    override func awakeFromNib() {
        super.awakeFromNib()
        EventosConfigurator.configure(viewController: self)
    }

    static func instantiate() -> EventosViewController {
        let storyboard = UIStoryboard(name: "Eventos", bundle: nil)
        let viewController = storyboard.instantiateInitialViewController() as! EventosViewController
        return viewController
    }

}

class EventosConfigurator {

    // MARK: - Configuration

    static func configure(viewController: EventosViewController) {

        let presenter = EventosPresenter()
        presenter.viewController = viewController

        let interactor = EventosInteractor()
        interactor.presenter = presenter

        let router = EventosRouter()
        router.viewController = viewController
        router.interactor = interactor

        viewController.interactor = interactor
        viewController.router = router
    }

}
