//
//  EventosCells.swift
//  Asistencia
//
//  Created by Fabrizio on 9/4/19.
//  Copyright (c) 2019 Fabrizio Valdivia. All rights reserved.
//
//  This file was generated by the StartApps CleanSwift Xcode Templates. V2.0
//  By Gabriel Lanata (http://StartApps.pe) with credit to http://clean-swift.com
//

import UIKit

class EventosCollectionViewCell: UICollectionViewCell {

    static let identifier = "EventosCollectionViewCell"
    @IBOutlet weak var nameLabel: UILabel!
    @IBOutlet weak var imageView: UIImageView!
    @IBOutlet weak var contentainerView: UIView!
    
    
    // @IBOutlet weak var iconImageView: UIImageView!
    //@IBOutlet weak var nameLabel:    UILabel!
    // @IBOutlet weak var contentLabel:  UILabel!

    override func awakeFromNib() {
        super.awakeFromNib()
        // Configure cell initial setting
    }

//    var displayedSomething: EventosScene.Eventos.ViewModel.DisplayedSomething! {
//        didSet {
//            // Configure cell from object
//            // iconImageView.image = displayedSomething.image
//        }
//    }

}
