//
//  EventosRouter.swift
//  Asistencia
//
//  Created by Fabrizio on 9/4/19.
//  Copyright (c) 2019 Fabrizio Valdivia. All rights reserved.
//
//  This file was generated by the StartApps CleanSwift Xcode Templates. V2.0
//  By Gabriel Lanata (http://StartApps.pe) with credit to http://clean-swift.com
//

import UIKit

class EventosRouter {

    weak var viewController: EventosViewController?
    weak var interactor: EventosInteractor?

    // MARK: - Navigation

    func navigateToSomewhere(id: Int, fechas: [EventDate], title: String, add: Bool, attendeeType: [String]) {
        // NOTE: Teach the router how to navigate to another scene. Some examples follow:

        // 1. Trigger a storyboard segue
        // viewController?.performSegueWithIdentifier("ShowSomewhereScene", sender: nil)

        // 2. Present another view controller programmatically
        // viewController?.presentViewController(someWhereViewController, animated: true, completion: nil)

        // 3. Ask the navigation controller to push another view controller onto the stack
        // viewController?.navigationController?.pushViewController(someWhereViewController, animated: true)

        // 4. Present a view controller from a different storyboard
        // let storyboard = UIStoryboard(name: "OtherThanMain", bundle: nil)
        // let someWhereViewController = storyboard.instantiateInitialViewController() as! SomeWhereViewController
        // viewController?.navigationController?.pushViewController(someWhereViewController, animated: true)

        // 5. Present a view controller from a different storyboard the StartApps way (preferred)
        // let someWhereViewController = SomeWhereViewController.instantiate()
        // viewController?.navigationController?.pushViewController(someWhereViewController, animated: true)
        
        let storyboard = UIStoryboard(name: "ListaAlumnos", bundle: nil)
        let listadoViewController = storyboard.instantiateViewController(withIdentifier: "ListaAlumnosViewController") as! ListaAlumnosViewController
        listadoViewController.interactor.id = id
        listadoViewController.interactor.fechas = fechas
        listadoViewController.title = title
        listadoViewController.canAddAttendee = add
        listadoViewController.attendeeType = attendeeType
        viewController?.navigationController?.pushViewController(listadoViewController, animated: true)
    }

    // MARK: - Communication

    func passDataToNextScene(segue: UIStoryboardSegue) {
        // NOTE: Teach the router how to pass data to the next scene
        // if let destinationViewController = segue.destination as? SomewhereViewController {
        //     destinationViewController.interactor.something = interactor?.something
        // }
    }

}
